#!/usr/bin/env bash
# if you see that the path is wrong, or the file name, etc is wrong, just edit it.
# you'll need libstrangle, and wine. and of course deltarune-
strangle 30 wine $HOME/.wine/drive_c/Program\ Files\ (x86)/SURVEY_PROGRAM/SURVEY_PROGRAM.exe
